/**
 * Enterprise Authentication System Constants
 */

export const AUTH_KEYS = {
  ACCESS_TOKEN_KEY: 'auth_access_token',
  REFRESH_TOKEN_KEY: 'auth_refresh_token',
  SESSION_KEY: 'auth_session_state',
  USER_PREFERENCE_KEY: 'auth_user_prefs',
  BROADCAST_CHANNEL: 'auth_session_sync_channel',
} as const;

export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  EXPIRED_SESSION: 'AUTH_EXPIRED_SESSION',
  EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  USER_EXISTS: 'AUTH_USER_EXISTS',
  VERIFICATION_FAILED: 'AUTH_VERIFICATION_FAILED',
  RECOVERY_FAILED: 'AUTH_RECOVERY_FAILED',
  PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
  NETWORK_ERROR: 'AUTH_NETWORK_ERROR',
  UNKNOWN: 'AUTH_UNKNOWN',
} as const;

export const SESSION_CONFIG = {
  IDLE_TIMEOUT_MS: 15 * 60 * 1000, // 15 Minutes
  REFRESH_INTERVAL_MS: 4 * 60 * 1000, // 4 Minutes
  MAX_RETRY_ATTEMPTS: 3,
} as const;
